### ISSUE TITLE
Why is this better than generic_hygrostat?

### ISSUE THREAD

**Issue by KTibow** [adrianByv/home-assistant-custom-components-switch-humidifier#3]
You can already copy+paste the `generic_hygrostat` component's pending PR, which seems more official, and once it's added you only have to delete `custom_components/generic_hygrostat` because config stays the same. Is there any better features in this?

**Comment by joshuata** [comment]
The generic hygrostat has a couple of missing features - first of all, it simply creates a sensor that detects whether temperature is within bounds - any additional actions must be written as automations. This component handles automating the switch internally so that no additional setup is needed.

More importantly to me, this component shows up as a humidifier/dehumidifier type in homeassistant. This means that all the existing widgets and HomeKit are supported for Apple devices. This isn't possible currently for the other component

**Comment by KTibow** [comment]
I think we might be miscommunicating.
This is the PR I mean: https://github.com/home-assistant/core/pull/36759
Here's the docs: https://deploy-preview-13876--home-assistant-docs.netlify.app/integrations/generic_hygrostat/
> This isn't possible currently for the other component

This is what I get:
![image](https://user-images.githubusercontent.com/10727862/104027356-22687e00-517c-11eb-91a9-e1694e68d42b.png)

**Comment by joshuata** [comment]
Gotcha. I was looking at an older pull request based on https://github.com/basschipper/homeassistant-generic-hygrostat. The biggest difference I can see right now is mostly that this can be easily installed using HACS, where it looks like integration of the other has stalled. Other than that, they look pretty similar

**Comment by KTibow** [comment]
Got it. Thanks!
